dev

diff --git a/concert-upload-ci.yaml b/concert-upload-ci.yaml
--- a/concert-upload-ci.yaml
+++ b/concert-upload-ci.yaml
@@ -121,11 +121,6 @@ spec:
       script: |
         #!/bin/bash
 
-        if ! command -v jq 2>&1 /dev/null; then
-          echo "install jq"
-          snap install jq
-        fi
-
         IMAGE_PATH=$(echo ${IMAGE_URL} | cut -d ':' -f 1)
         CYCLONEDX_SBOM=$WORKSPACE/concert/$(basename ${IMAGE_PATH})-sbom.json
 
@@ -152,37 +147,6 @@ spec:
 
         if [ ! -s ${CYCLONEDX_SBOM} ]; then
           echo "SBOM file is empty: ${CYCLONEDX_SBOM}"
-          exit 1
-        fi
-
-        # Replace SBOM component name with image path+tag
-        #
-        jq ${CYCLONEDX_SBOM} \
-          --arg img_url ${IMG_URL} '
-            .metadata.component.name = $img_url
-          ' > $tempfile
-        cp $tempfile ${CYCLONEDX_SBOM}
-
-        ###
-        # Upload CycloneDX-formatted image package SBOM to Concert
-        #
-        UPLOAD_URL=$(cat ${WORKSPACE_CONCERT_API}/endpoint-url)/ingestion/api/v1/upload_files
-        AUTH_TYPE=$(cat ${WORKSPACE_CONCERT_API}/key-type)
-        AUTH_KEY=$(cat ${WORKSPACE_CONCERT_API}/key-value)
-        curl -X POST -sS "${UPLOAD_URL}" \
-          -H 'accept: application/json' \
-          -H "InstanceID: $(cat ${WORKSPACE_CONCERT_API}/instance-id)" \
-          -H "Authorization: ${AUTH_TYPE} ${AUTH_KEY}" \
-          -H 'Content-Type: multipart/form-data' \
-          -F "data_type=package_sbom" \
-          -F "filename=@${CYCLONEDX_SBOM}" \
-          2>&1 > $tempfile
-
-        if [[ $? == 0 ]]; then
-          echo "Successfully uploaded image package SBOM to Concert"
-        else
-          echo "Failed to upload image package SBOM to Concert"
-          cat $tempfile
           exit 1
         fi
 
@@ -221,6 +185,41 @@ spec:
         echo "Defined Environment Varaibles"
         printenv
         echo "------"
+
+        IMAGE_PATH=$(echo ${IMAGE_URL} | cut -d ':' -f 1)
+        CYCLONEDX_SBOM=$WORKSPACE/concert/$(basename ${IMAGE_PATH})-sbom.json
+        if [ -s ${CYCLONEDX_SBOM} ]; then
+          # Replace SBOM component name with image path+tag
+          #
+          jq ${CYCLONEDX_SBOM} \
+            --arg img_url ${IMG_URL} '
+              .metadata.component.name = $img_url
+            ' > $tempfile
+          cp $tempfile ${CYCLONEDX_SBOM}
+
+          ###
+          # Upload CycloneDX-formatted image package SBOM to Concert
+          #
+          UPLOAD_URL=$(cat ${WORKSPACE_CONCERT_API}/endpoint-url)/ingestion/api/v1/upload_files
+          AUTH_TYPE=$(cat ${WORKSPACE_CONCERT_API}/key-type)
+          AUTH_KEY=$(cat ${WORKSPACE_CONCERT_API}/key-value)
+          curl -X POST -sS "${UPLOAD_URL}" \
+            -H 'accept: application/json' \
+            -H "InstanceID: $(cat ${WORKSPACE_CONCERT_API}/instance-id)" \
+            -H "Authorization: ${AUTH_TYPE} ${AUTH_KEY}" \
+            -H 'Content-Type: multipart/form-data' \
+            -F "data_type=package_sbom" \
+            -F "filename=@${CYCLONEDX_SBOM}" \
+            2>&1 > $tempfile
+
+          if [[ $? == 0 ]]; then
+            echo "Successfully uploaded image package SBOM to Concert"
+          else
+            echo "Failed to upload image package SBOM to Concert"
+            cat $tempfile
+            exit 1
+          fi
+        fi
 
         ###
         # Generate & Upload ConcertDef Build Inventory SBOM
@@ -268,8 +267,6 @@ spec:
 
         # Add BOM-LINK for the image CycloneDX SBOM
         #
-        IMAGE_PATH=$(echo ${IMAGE_URL} | cut -d ':' -f 1)
-        CYCLONEDX_SBOM=$WORKSPACE/concert/$(basename ${IMAGE_PATH})-sbom.json
         if [ -s ${CYCLONEDX_SBOM} ]; then
           sbom_num=$(jq '.serialNumber' ${CYCLONEDX_SBOM})
           sbom_ver=$(jq '.version' ${CYCLONEDX_SBOM})
@@ -279,7 +276,7 @@ spec:
           jq ${BUILD_SBOM} \
             --arg sbom_link ${SBOM_LINK} '
               .components[0] += {"cyclonedx-bom-link": $sbom_link}
-            ' > $tempfile
+          ' > $tempfile
           cp $tempfile ${BUILD_SBOM}
         fi
 
